# Generated by Django 4.2.1 on 2023-07-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_desc_contact_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='Number',
        ),
    ]
