# Generated by Django 4.2.1 on 2023-07-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_contact_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date',
            new_name='date',
        ),
    ]
