# Generated by Django 4.2.1 on 2023-07-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_date_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Number',
            field=models.IntegerField(max_length=12),
        ),
    ]
