# Generated by Django 4.2.1 on 2023-08-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_form_remove_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Number',
            field=models.CharField(max_length=15),
        ),
    ]
